#pragma once
#include <map>
#include <list>
#include <unordered_map>
#include <string>
#include<vector>
#include<mutex> 
#include "Order.h"
#include "Trade.h"

class OrderBook {
public:
    explicit OrderBook(const std::string& symbol);
    // this will process the limit order and will return all the trades generated by this order
    // also if the order is not fully filled, the remaining quantity is stored in the book; 
    std::vector<Trade> add_limit_order(Order& order); 

    // returns all the trade generated by this order and process the market order
    std::vector<Trade> process_market_order(Order& order);
    bool cancel_order(unsigned long long order_id); // for cancelling a non fullfilled limit order in the list; 
    int best_buy_price() const; // highest price and first time stamp, if not available return -1
    int best_sell_price() const; // lowest price and first time stamp, if not available return -1; 
    const std::string& get_symbol() const; // returns the symbol of current OrderBook; 

private:
    // this ensures that the each corresponding order is processed sequentially! 
    mutable std::mutex mtx; // this is not the logical state, can change this by lock() / unlock (); 

    // note -- the below function will not actually add the limit order to the list , it is being done by the add_limit_order, 
    // the below function i added later to reduce the repeated code
    std::vector<Trade> match_buy_order(Order& buy_order); // prcess the buy order
    std::vector<Trade> match_sell_order(Order& sell_order); // actually process the sell order

    std::string symbol;
    std::map<int, std::list<Order>, std::greater<int>> buy_book; // the data structure that maintains the unfuillfilled list of limit buy order in fifo and best price manner; 
    std::map<int, std::list<Order>> sell_book;  // similar to buy_book ds , but for the selling of the order; 

    // this is maintained for the fast cancellation, it stores information of each order so we can cancel it immediately; 
    struct OrderLocation {  // data structure for each order which contain information that where this order is currently located; 
        bool is_buy;
        int price; // needed for map level
        std::list<Order>::iterator it; // will directly delete from this itterator whenever we need to delete some order; 
    };

    std::unordered_map<unsigned long long, OrderLocation> order_index; 
};
